### ISSUE TITLE
ERROR: Result too large

### ISSUE THREAD

**Issue by NathanVanderau** [Blacksmoke16/GESI#102]
When using the corporations_corporation_assets() function, I get a result of "#ERROR!" with tool-tip text stating "Error: Result too large."

**Comment by Blacksmoke16** [comment]
This error means you have so many assets, you're hitting the cell limit in sheets. Nothing I can do about it. Your best bet would be to use a custom function to work with the raw data to avoid needing to dump _everything_ to the sheet itself.

**Comment by NathanVanderau** [comment]
I'm not sure this is the issue. Sheets has a cell limit of 10,000,000 cells per sheet. I know that the corp doesn't have 1,000,000 unique assets. Auth is showing 61,744 objects returned. GET /corporations/{corporation_id}/assets/ returns 8 key/value pairs per object. So, just under 500,000 cells.
While I can manually copy the Auth data to a sheet in Sheets, simply using GESI is so much cleaner.

**Comment by Blacksmoke16** [comment]
Maybe not the exact issue, but I am able to reproduce it by just trying to return 61,744 rows of static mock asset data. Maybe there's a limitation on the size of the return value from a custom function :shrug:.

I'd still consider following https://github.com/Blacksmoke16/GESI#script-editor, then leverage https://github.com/Blacksmoke16/GESI#built-in-functions `invokeRaw` in your own custom function such that you can do what you want with code and ultimately return only the records you care about or the calculations of whatever you are wanting to do.
