### ISSUE TITLE
Access token validation error: invalid audience (line 61, file "esi_client")

### ISSUE THREAD

**Issue by alexanderjacuna** [Blacksmoke16/GESI#104]
Seeing the error below when authorizing first character.

```
Google Apps Script
Access token validation error: invalid audience (line 61, file "esi_client")
```

Steps to reproduce:
1. Install the GESI add-on.
2. Select "Authorize Character" in the dropdown.
3. Login via EVE Online SSO.
4. Immediately after authenticating with first character the error appears. 

![googleappsscripterror](https://github.com/Blacksmoke16/GESI/assets/38297159/2938b4da-204e-43ff-9ae7-0c272660283c)

**Comment by Blacksmoke16** [comment]
It seems https://docs.esi.evetech.net/docs/sso/validating_eve_jwt.html#validate-the-audience-claim is no longer accurate as the value of the `aud` claim is:

```json
[
  "683084ab5f8848d4b187462ac3b97677",
  "EVE Online"
]
```

I've raised this in the partner program discord to see if its a bug, intended, or what.

**Comment by Blacksmoke16** [comment]
As per https://github.com/esi/esi-docs/pull/77, this is now expected. I'll update the validation logic and get a new release out.

**Comment by Blacksmoke16** [comment]
Fixed in https://github.com/Blacksmoke16/GESI/releases/tag/9.2.1.
