### ISSUE TITLE
Access token validation error: invalid issuer (line 60, file "esi_client")

### ISSUE THREAD

**Issue by c0pp3r** [Blacksmoke16/GESI#105]
Getting the error in the subject when attempting to re-auth a sheet that seemed to have lost auth. Have tried resetting and re-authing with no luck

**Comment by lewiseves** [comment]
How did you fix it?

**Comment by Blacksmoke16** [comment]
This is the result of a change in the `iss` claim of the token. Unfortunately I'm currently on holiday and the app script editor is essentially useless on mobile. So I won't be able to fix it until I get home on the 7th.

**Comment by TinkeringGoblin** [comment]
same issue here! glad to see its being worked on already, thank you for all you do.

**Comment by Blacksmoke16** [comment]
This is resolved.
