### ISSUE TITLE
To many requests

### ISSUE THREAD

**Issue by Apexofacircle** [Blacksmoke16/GESI#108]
`Exception: Service invoked too many times for one day: urlfetch. (line 43).` is the error I am getting. Is there a way to slow down the API calls? Is there a way to store the information in a cash and call it once per cycle designated by the user? This is my code:`=markets_prices()`. 
![image](https://github.com/Blacksmoke16/GESI/assets/96547482/4c9b2386-942e-434b-abd6-d835339fe0cb)

**Comment by Blacksmoke16** [comment]
I find it hard to believe you're running into that error solely via `markest_prices` unless you're refreshing it like every minute as its only a single request each time. 

Keep in mind this limit is account wide, so this sheet might not be the one using up your quota.

**Comment by Apexofacircle** [comment]
I just discovered that there was a sheet in the background full of api calls. Thanks for the reply!

**Comment by arseniy-gl** [comment]
@EroldHareka, I suggest throttling API requests.
