### ISSUE TITLE
Authentication Error when logging into specific character

### ISSUE THREAD

**Issue by IronForce-Auscent** [Blacksmoke16/GESI#109]
When logging in with my alt corp CEO, I get the following error: Error: {"error":"authentication failure"} (line 254). The error only occurs on that character, and all other characters can use the API perfectly fine

Function being used:
=corporations_corporation_wallets(ALT_CORP_CEO_CHARACTER_NAME, True)

**Comment by Blacksmoke16** [comment]
What happens if you re-auth that char? I.e. go thru the auth process again for them.

**Comment by IronForce-Auscent** [comment]
Error still pops up even after re-authentication. I've also tried de-authing and re-authing and the error persists. It could be that it's an issue with this particular character name that causes the error, since it has a dash in the name

**Comment by Blacksmoke16** [comment]
Might also be worth trying the `Reset` option if you don't have too many chars authed.

If the error is still happening after that, I'd need some additional info to go on I think. If you're on the GESI discord can PM me and can work thru it so you don't have to expose stuff here.

**Comment by Blacksmoke16** [comment]
We looked into this more and ultimately is an instance of https://github.com/esi/esi-issues/issues/1089. Workaround was to limit the required scopes via https://github.com/Blacksmoke16/GESI?tab=readme-ov-file#how-can-i-limit-what-scopes-are-used.
