### ISSUE TITLE
corporationExtractions()

### ISSUE THREAD

**Issue by warriorsoul15** [Blacksmoke16/GESI#11]
This function seems to output the headers but thats it. No adjustment to the variables gives any data.

**Comment by Blacksmoke16** [comment]
@warriorsoul15 Would you mind giving me edit access on a sheet of yours to test this?  My corp doesn't have any refineries up so can't really test it.

**Comment by warriorsoul15** [comment]
I am not sure how to do this semi-securely ;)  but my ESI login is for the corp CEO so there should not be a roles issue.

**Comment by Blacksmoke16** [comment]
Convo me in game and we can chat about it.  Same name as my Github.

**Comment by warriorsoul15** [comment]
will try
