### ISSUE TITLE
corporationObserverMining - Feature request

### ISSUE THREAD

**Issue by warriorsoul15** [Blacksmoke16/GESI#12]
Would it be possible to make a new function or modify this one to do a few things,  first enumerate the corporationObservers() function then dump the corporationObserverMining() to ALL observer IDs, and ideally specify a date-range in the output?  Ideally also doing lookups for the Refinery name, and character name from their respective IDs.
That would be sweet.

**Comment by Blacksmoke16** [comment]
Go right ahead.  

However, it isn't something I would do.  I want to keep the script limited to just getting the data from ESI.  If the end user wants to modify it to better fit their needs they are free to do so.
