### ISSUE TITLE
Header Flag not Working

### ISSUE THREAD

**Issue by AbsoluteTruth** [Blacksmoke16/GESI#13]
If you set headers to false in any function that has getarrayobjectresponse instead of getobjectresponse, there is no output at all. For instance, the skillQueue function.

**Comment by AbsoluteTruth** [comment]
The fix is to comment out the following lines in getArrayObjectResponse_:

    if (result.length === 0) return null;
    if (data.length === 0) return result;

If these lines are commented out, the header flag works perfectly.

**Comment by Blacksmoke16** [comment]
I made a commit yesterday 761c5aaf396ea2f222bfd38b64f1c092620aa735

Try replacing those two lines with the new stuff and it should work better.

**Comment by AbsoluteTruth** [comment]
New update fixes the problem. Thank you.
