### ISSUE TITLE
"GESI" Menu Item goes away

### ISSUE THREAD

**Issue by chronark** [Blacksmoke16/GESI#17]
After some time the "GESI" entry in the menu just disappears, Instead there's a dropdown menu called "Script Center Menu" with the only entry "Read Data".

Clicking on "Read Data" doesn't seem to do anything.

All functions simply return "FALSE" without any error message.

**Comment by Blacksmoke16** [comment]
Are you using any other scripts besides GESI?

**Comment by chronark** [comment]
.. I feel stupid now :)
Everything works like a charm now, thank you!

I had a script to read json data and apparently that caused the issue.
