### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by multru** [Blacksmoke16/GESI#18]
Do you have a plans to add POST requests to ESI, like a /v2/universe/names/ ?

**Comment by Blacksmoke16** [comment]
Possibly in the future.  Main reason for not including them now is how to handle the one off nature of them.  

For example GET requests return data every time, while POST request are usually a one time thing, i.e. you wouldn't want your destination to change every time you load the page.

Current idea for that would be to have the request happen, then delete it from the cell that called it upon success.  More dev will be required to test this and make sure everything works as expected.
