### ISSUE TITLE
Option to fetch all pages for contracts fails to return first page

### ISSUE THREAD

**Issue by AbsoluteTruth** [Blacksmoke16/GESI#19]
When fetching all contracts available to a corporation using the following command:

=corporations_corporation_contracts("characterName",-1)

The -1 option fetches all pages EXCEPT the first page. I believe that the -1 option is supposed to fetch all pages.

**Comment by Blacksmoke16** [comment]
Oo good catch.

**Comment by AbsoluteTruth** [comment]
Now when you use the -1 option, it only gets the first page and not the rest.

**Comment by Blacksmoke16** [comment]
lol, sigh.  Give me a few.

**Comment by Blacksmoke16** [comment]
Alright, try that now :P

**Comment by AbsoluteTruth** [comment]
Confirmed fixed. Thanks!
