### ISSUE TITLE
Output from characters_character_skills function is not parsed correctly

### ISSUE THREAD

**Issue by AbsoluteTruth** [Blacksmoke16/GESI#20]
When using the =characters_character_skills(charName) function, the output is split into three columns - Skills, Total SP, Unallocated SP. All of the skills returned appear unformatted in the same cell in the "Skills" column instead of appearing spread out down the whole column. I'm not sure if this is intentional but it hinders the usefulness of the function.

**Comment by Blacksmoke16** [comment]
This is intentional due to the skills endpoint returning a nested array. I.e. there is not a clean way to display that kind of structure in a 2D spreadsheet.

Check out the `=parseArray()` function in the readMe.

**Comment by AbsoluteTruth** [comment]
I read through the readme and i'm having issues with the parseArray() syntax. Can you provide an example of what this function would look like?

**Comment by Blacksmoke16** [comment]
https://github.com/Blacksmoke16/GESI/blob/master/GESI.gs#L115-L123

`=parseArray(FUNCTION_NAME, COLUMN_NAME, COLUMN)`

**Comment by AbsoluteTruth** [comment]
I tried: =parseArray(characters_character_skills,"skills",Testing!A:A) and got an error, "Cannot read property 'headers' from undefined"

**Comment by Blacksmoke16** [comment]
the function name should be in quotes as well.  So like 

`=parseArray("characters_character_skills","skills",Testing!A2)`

**Comment by AbsoluteTruth** [comment]
That worked perfectly. Thank you.
