### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Errious** [Blacksmoke16/GESI#24]
I tried to call =characters_character_mining( and got this:
[https://i.imgur.com/wbVE03z.png](https://i.imgur.com/wbVE03z.png)
[https://i.imgur.com/SSXQ1yg.png](https://i.imgur.com/SSXQ1yg.png)

**Comment by Blacksmoke16** [comment]
Did you auth the character you are trying to use?  I.e. is that character in the `Auth Data` sheet?

**Comment by Errious** [comment]
meh, i used the wrong character, sorry!

But i get urlfetch error direct but did not used any docs since a couple days?

**Comment by Blacksmoke16** [comment]
I'm not sure what you mean?

**Comment by Errious** [comment]
I was going to try the new version and have not used gdocs on my home pc a couple days, as i tried now, i get instant the message i hitted the url fetch limit, you know, the sh**** that tells you can not work today because something is wrong :-) url fetch error... Service invoked to many times for one day.

**Comment by Blacksmoke16** [comment]
Ah, it must update in the background then.  There isn't really much I can do about that.  Possibly look into developing your own app if Google sheets can't handle what you need.

Anyway im going to close this issue since it is already resolved.
