### ISSUE TITLE
internal error executing 'corporations_corporation_assets' with page=-1

### ISSUE THREAD

**Issue by sapyx** [Blacksmoke16/GESI#27]
using the "corporations_corporation_assets" function with page = -1, the error 'Internal error when executing the custom function.' is reported in the cell. My corporation usually has more than 20 pages (25, 28). Some advice?

**Comment by Blacksmoke16** [comment]
This usually happens when there is a large amount of data to return/parse.  I can reproduce it getting market orders from The Forge.  Will look into either fixing it or providing a better error message if this is a limit within Sheets itself.

**Comment by Blacksmoke16** [comment]
@sapyx Can you try creating a new google sheets, setting up GESI and see if you get the same error?

**Comment by sapyx** [comment]
same error, but the files on github aren't changed

**Comment by Blacksmoke16** [comment]
I have been poking around at this, from what I can tell it is one of the following:

1. The endpoint hits the 30 sec runtime limit of a custom function
2. There are too many cells in the sheet OR returning all the data would make the workbook have too many cells. (is a 2m cell limit, inclusive of all sheets in a Google Sheet doc)
3. There is some size limit that a scripts array or something can contain/process.

I'll keep messing with it but as of now im not so sure i can do anything about it.  Possibly you could something like https://github.com/Blacksmoke16/GESI#using-functions-with-multiple-characters to create functions that wrap x pages of an endpoint. This way it would be split up and sheets could handle it better.

**Comment by sapyx** [comment]
I believe the cause is the 30 second timeout for user functions.
fetch works for up to 7 / 10 pages

**Comment by sapyx** [comment]
I tried this, but always reports the same error;
```
function filteredCorporationAssets(name, filterList, opt_headers) {
    var endpoint_name = "corporations_corporation_assets"; 
    var endpoint = ENDPOINTS[endpoint_name];
  
    var data = [];
    var result = [];

    if (opt_headers || undefined === opt_headers) result.push(endpoint.headers.map(function(h) { return h.name }));
  
    var page = 1;
    var response = getData_(endpoint_name, {name:name,page:page,opt_headers:opt_headers})
    var assets = response.data; 
  
// -------------
    var filterListLength = filterList.length;  
  
    for (var i=0;i<assets.length;i++){
      for (var j=0;j<filterListLength;j++){
          if (assets[i].type_id == filterList[j][0]){
              data.push(assets[i]);
          }
      }
  }
// -------------    
    
    var pages = parseInt(response.headers['x-pages']);
  
    for (var page = 2; page <= pages; page++) {
        assets = getData_(endpoint_name, {name:name,page:page,opt_headers:opt_headers}).data;
        // -------------  
        for (var i=0;i<assets.length;i++){
            for (var j=0;j<filterListLength;j++){
                if (assets[i].type_id == filterList[j][0]){
                    data.push(assets[i]);
                }
            }
        }
        // -------------
    }       
  
    data.forEach(function(obj) {
        var temp = [];
        endpoint.headers.forEach(function(header) {
            temp.push(parseObject_(obj, header));
        });
       result.push(temp);
    });
      
    return result;
}
```

**Comment by Blacksmoke16** [comment]
I was thinking something like

```JavaScript
function getAssets(startPage, endPage) {
  var data = [];
  for (var page = startPage; page <= endPage; page++) {
    data = data.concat(corporations_corporation_assets(null, page, false));
  }
}
```
Then can call it like `=getAssets(1,7)` where that would return assets pages 1 thru 7, then could call it again for next 7 like `=getAssets(8,14)`.  Not really optimal but not much i can do about that limit :/

**Comment by sapyx** [comment]
true, but you can not know in advance how many pages will be returned by the API

**Comment by Blacksmoke16** [comment]
No but it does not really matter.  The functionality is exactly the same.

**Comment by sapyx** [comment]
humm... no!
to replicate the behavior of the -1, I MUST know, at the time of creating the sheet, the number of pages returned by the API. But, being the response variable , it is impossible.

**Comment by Blacksmoke16** [comment]
You don't have to.  You could do something like this:
```JavaScript
function getAssets(startPage, endPage) {
  var assets = [];
  for (var page = startPage; page <= endPage; page++) {
    var a = corporations_corporation_assets(null, page, false);
    assets = assets.concat(a);
    if (a.length < 1000) break;
  }
  return assets;
}
```
If you request a page higher than the actual number of pages it would just come back empty and break out of the loop.  This also covers the last page that would have less than 1000 results (for this specific endpoint).  Of course there are a few suboptimal issues with this, such as making a few more calls than the `-1` param but overall the functionality is exactly the same provided you make enough of the function to account for the highest possible amount of pages.

For example if on average you get 25 pages, with it able to get 7 pages within 30 sec you could use 4 functions,

1. 1-7
2. 8-14
3. 15-21
4. 22-28

If you really wanted you could add in logic like `if (endPage === page && a.length === 1000) throw 'Need more functions to cover additional pages';` This way if you end up getting 30 pages the last function would throw an error telling you that you need to add more functions to cover pages 29-35.

**Comment by sapyx** [comment]
mmmmh! it's like an hack, but i can try. This breaks the automatism of a complex sheet, but if there is no other way ...

**Comment by Blacksmoke16** [comment]
mhm.  I wouldn't call it a hack, just not as simple as using `-1` but considering i can't do anything about the 30 sec limit this is best you got. 

Imma close this issue.

**Comment by Blacksmoke16** [comment]
As reference for others visiting this issue see https://github.com/Blacksmoke16/GESI#internal-error-when-executing-the-custom-function

**Comment by AbsoluteTruth** [comment]
You can work around this issue. The run time of a google apps script is 5 minutes, whereas for a function it's 30 seconds. What I do is make a second script that writes the output of the first to a sheet, and then assign that to a button on my spreadsheet. That way you avoid using functions and do everything entirely in GAS, and the Google sheet is only used for the output itself.
