### ISSUE TITLE
error on system request

### ISSUE THREAD

**Issue by kilann** [Blacksmoke16/GESI#28]
Hi

when i use =universe_systems_system(,Q3,true)
i have an error than i havent yesterday 

ESI response error: {"error":"Invalid 200 response: 'star_id' is required","code":500} (ligne 202).

value in Q3 : 30000142

**Comment by Blacksmoke16** [comment]
This is a known issue with ESI.

See https://github.com/esi/esi-issues/issues/944

**Comment by Blacksmoke16** [comment]
@kilann This should be fixed on ESI's end now.

**Comment by kilann** [comment]
problem is solved for now 

thank you for your work, it's amazing

just another question:
do you kwon a way to have a system id from the system name with esi ?


Le 31/05/2018 18:17:29, Blacksmoke16 <notifications@github.com> a écrit :
@kilann [https://github.com/kilann] This should be fixed on ESI's end now.

**Comment by Blacksmoke16** [comment]
`=eve_search("solar_system",,"Jita",true)`

You could probably create a custom function that wraps `eve_search` function where you pass it a systemName, it looks it up like my example, then just returns the first result in the `solar_system` array.

**Comment by kilann** [comment]
Hi

=eve_search("solar_system",,"Jita",true)
work perfectly :)
ty

another question : is there a way to send a mail from the sheet to a player or mailing list ?
Le 31/05/2018 18:49:23, Blacksmoke16 <notifications@github.com> a écrit :
=eve_search("solar_system",,"Jita",true)
You could probably create a custom function that wraps eve_search function where you pass it a systemName, it looks it up like my example, then just returns the first result in the solar_system array.

**Comment by Blacksmoke16** [comment]
Yes but POST endpoints are not implemented yet due to the nature of how they would work.  You are free to add your own function to do it.  It shouldn't be too hard.

See https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail

**Comment by kilann** [comment]
I'm on it
If i find a way i send you the fonction but i think you'll find before me :)
Le 05/06/2018 01:08:45, Blacksmoke16 <notifications@github.com> a écrit :
Yes but POST endpoints are not implemented yet due to the nature of how they would work. You are free to add your own function to do it. It shouldn't be too hard.
See https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail [https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail]

**Comment by kilann** [comment]
Hi

sorry to bother you again

here is the custom fonction have made

have an error how say  " sign ; missing before instruction on ligne 1"
i cant find the error

thank for help

  "characters_character_send_mail": {
    "description": "Sending Mail",
    "summary": "Send Mail",
    "request": "post",
    "version": 1,
    "headers": [
      {
        "name": "character_id",
        "type": "integer"
      },
      {
        "name": "datasource",
        "type": "string"
      },
      {
        "name": "mail",
        "type": "array",
        "sub_heaters":[
          "approved_cost",
          "body",
          {
          "name": "recipients",
          "type": "array",
          "sub_headers": [
            "recipient_id",
            "recipient_type"
             ]
           },
          "subject";
          ]
      },
    ]
    "path": "/v1/characters/{character_id}/mail/",
    "authed": true,
    //"response_type": "array",
    "item_type": "object",
    "parameters": [
      {
        "name": "character_id",
        "description": "Reciever Id",
        "required": true,
        "type": "integer",
        "in": "query"
      },
      {
        "name": "datasource",
        "description": "tranquility, singularity",
        "required": true,
        "type": "string",
        "in": "query"
      },
      {
        "name" : "approved_cost",
        "description": "Approved cost for sending mail",
        "requiered": false,
        "type": "integer"
      },
      {
        "name": "body",
        "description":"Mail to send, maxLength: 10000",
        "requiered": true,
        "type": "string"
      },
      {
        "name":"recipient_id",
        "description": "recipient id",
        "requiered" : true,
        "type": "integer"
      },
      {
        "name": "recipient_type",
        "description": "recipient type, alliance, character, corporation, mailing_list",
        "requiered": true,
        "type":  "string"
      },
            
      {
        "name": "subject",
        "description": "subject of mail, maxLength: 1000",
        "requiered": true,
        "type": "string"
      },
     ]
  }
Le 05/06/2018 01:11:39, olivier.death <olivier.death@gmail.com> a écrit :
I'm on it
If i find a way i send you the fonction but i think you'll find before me :)
Le 05/06/2018 01:08:45, Blacksmoke16 <notifications@github.com> a écrit :
Yes but POST endpoints are not implemented yet due to the nature of how they would work. You are free to add your own function to do it. It shouldn't be too hard.
See https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail [https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail]

**Comment by Blacksmoke16** [comment]
You probably dont have to do any of this.  I meant just make a custom function in GESI.gs

like
```JavaScript
function sendMail(to, subject, message) {
  // build out and send the mail.
  // see https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String) 
  // Make a POST request with a JSON payload.
}

**Comment by kilann** [comment]
i'm realy noob on script, i get this error 

Query failed for https://esi.tech.ccp.is/v1/characters/96377439/mail/. Code returned: 403. Server truncated response: {"error": "Token is not valid for scope: esi-mail.send_mail.v1", "sso_status": 200} (Use the muteHttpExceptions option to examine the entire response. ) (line 376).

added "esi-mail.send_mail.v1" to the scope list

function sendMail(recipient_id,recipient_type, subject, message) {
  // build out and send the mail.
  // see https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String) 
  // Make a POST request with a JSON payload.

 var data = {
   'Recipient': [recipient_id,recipient_type],
   'subject': subject,
   'message': message
 };
  var name = MAIN_CHARACTER;
  var token = CACHE.get(name + '_access_token');
  var auth = token ? 'Bearer ' + token : 'Basic ' + Utilities.base64EncodeWebSafe(CLIENT_ID + ':' + CLIENT_SECRET)
  var options = {'method': 'post', 'muteHttpExceptions': false, headers: {'User-Agent': 'GESI user ' + SpreadsheetApp.getActiveSpreadsheet().getOwner().getEmail(),'Content-Type': 'application/json','Authorization': auth},
   // Convert the JavaScript object to a JSON string.
  'payload' : JSON.stringify(data)};
 
 UrlFetchApp.fetch('https://esi.tech.ccp.is/v1/characters/96377439/mail/', options);
}



Le 05/06/2018 23:45:25, Blacksmoke16 <notifications@github.com> a écrit :
You probably dont have to do any of this. I meant just make a custom function in GESI.gs
like
function sendMail(to, subject, message) { // build out and send the mail. // see https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String) // Make a POST request with a JSON payload. }

**Comment by Blacksmoke16** [comment]
Well yes, that scope doesnt come by default.  You need to add it to the scopes array then reauth that char.

**Comment by kilann** [comment]
Hi

have well work, i think but still have an error 

{"error":"Character ID mismatch between request path and auth token"}

i have well put my character id in the formula

if you know where is the problem...

thank in advance

function sendMail(sender_id,datasource,recipient_id,recipient_type, subject, body) {
  // build out and send the mail.
  // see https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetch(String) 
  // Make a POST request with a JSON payload.
  var name = MAIN_CHARACTER;
  var token = CACHE.get(name + '_access_token');

 var data = {
   'character_id': sender_id,
   'datasource': datasource,
   'body':body,
   'recipient_id':recipient_id,
   'recipient_type':recipient_type,
   'recipients':[{'recipient_id':recipient_id,'recipient_type':recipient_type}],
   'subject':subject,
   'mail':{'body':body,'recipients':{'recipient_id':recipient_id,'recipient_type':recipient_type},'subject':subject},
   'token':token
};
  
  
  Logger.log(data)
  var name = MAIN_CHARACTER;
  var token = CACHE.get(name + '_access_token');
  var auth = token ? 'Bearer ' + token : 'Basic ' + Utilities.base64EncodeWebSafe(CLIENT_ID + ':' + CLIENT_SECRET)
  var options = {'method': 'post', 'muteHttpExceptions': false, headers: {'User-Agent': 'GESI user ' + SpreadsheetApp.getActiveSpreadsheet().getOwner().getEmail(),'Content-Type': 'application/json','Authorization': auth},
   // Convert the JavaScript object to a JSON string.
  'payload' : JSON.stringify(data)};
  
  Logger.log(JSON.stringify(data))
 
 UrlFetchApp.fetch('https://esi.tech.ccp.is/v1/characters/96377439/mail/', options);
}

**Comment by Blacksmoke16** [comment]
It's using the token of a diff char that you are using in the request.

Message me on discord, that would be easier than going back and forth `Blacksmoke16#0016`
