### ISSUE TITLE
Pulling names corpnames issues

### ISSUE THREAD

**Issue by Errious** [Blacksmoke16/GESI#32]
After ESI got an Update and some Endpoints like character_names and others have to be migrated into the '/v2/universe/names/' scope now, GESI is missing a replacement for this.

One temporary workaround was Blacksmoke´s idea with this code snippet:

/** 
* Resolve a set of IDs to names and categories. Supported ID’s for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.
* @param {array} The ids to resolve.
* @return List of id/name associations for a set of ID’s.
* @customfunction
*/
function names(ids) {
  var data = doRequest_(BASE_URL + '/v2/universe/names/', 'POST', null, ids.map(function(id) { return id[0]; }));
  var response = [];
  data.data.forEach(function(d) {
    var temp = [];
    temp.push(d['id']);
    temp.push(d['name']);
    response.push(temp);
  });
  return response;
}

But sadly this is not working if single cell conent want to be used, it is only working for a "range" of values.

A Solution would be nice to see :-)

**Comment by Blacksmoke16** [comment]
This is going to be relatively not easy to do since the endpoint that replaced the `*_names` endpoints is a POST request.  Up until now GESI does not have POST request support, so this will have to be introduced for this to work.

I'll have something out when i can.

**Comment by Blacksmoke16** [comment]
https://github.com/Blacksmoke16/GESI/blob/master/dist/functions.gs#L1853-L1863

Can use `=universe_names(ids)` now.
