### ISSUE TITLE
Multilevel json objects are not parsed beyond the first.

### ISSUE THREAD

**Issue by jamesjwilson** [Blacksmoke16/GESI#33]
Here is my test path to reproduce.

`=universe_systems_system(31001688, en-us, true)`

The `planets` cell has unparsed data.

```[{"planet_id":40438381},{"planet_id":40438382},{"planet_id":40438383},{"planet_id":40438384},{"moons":[40438386],"planet_id":40438385},{"moons":[40438388],"planet_id":40438387},{"moons":[40438390,40438391],"planet_id":40438389},{"moons":[40438393],"planet_id":40438392},{"moons":[40438395,40438396,40438397,40438398,40438399,40438400,40438401,40438402,40438403,40438404,40438405,40438406,40438407,40438408,40438409,40438410,40438411,40438412,40438413],"planet_id":40438394},{"moons":[40438415,40438416,40438417,40438418,40438419,40438420,40438421,40438422,40438423,40438424,40438425,40438426,40438427,40438428,40438429,40438430,40438431,40438432,40438433,40438434,40438435,40438436,40438437,40438438,40438439],"planet_id":40438414},{"moons":[40438441,40438442,40438443,40438444,40438445,40438446],"planet_id":40438440},{"moons":[40438448,40438449,40438450,40438451,40438452,40438453,40438454,40438455,40438456,40438457,40438458,40438459,40438460,40438461,40438462,40438463,40438464,40438465],"planet_id":40438447}]```

I'm not sure if I understand it 100% correctly if there should be a `planets` column and a `moons` column etc.  But hopefully, this is enough to explain the issue.

**Comment by Blacksmoke16** [comment]
This will be fixed in `7.0.0` when the add-on stuff gets released.
