### ISSUE TITLE
reorder headers

### ISSUE THREAD

**Issue by jonobrien** [Blacksmoke16/GESI#39]
So there used to be the option to modify the header ordering in endpoints, but this was removed from the [readme](https://github.com/Blacksmoke16/GESI/commit/b1c5cf22e25aeff42633e260feca9ee67bcc9602#diff-04c6e90faac2675aa89e2176d2eec7d8L133) with the migration to an add-on from the pure google-script implementation, do I have to manually copy and paste the scripts as in the paste to override the header ordering, or is this just not possible anymore?

I'm trying to modify which headers are optional and which are returned by default when opt_headers is False.
Just upgraded from v5.7

**Comment by Blacksmoke16** [comment]
@jonobrien It's possible, but you would have to use a custom function to handle the logic of what columns get returned when.

**Comment by Blacksmoke16** [comment]
@jonobrien Am going to close this now.  If you need more help with this feel free to mention me on the GESI discord.
