### ISSUE TITLE
Verify

### ISSUE THREAD

**Issue by DukaSoft** [Blacksmoke16/GESI#41]
I might be doing something wrong, but trying to authorize a charecter gives the following error:
The coordinates or dimensions of the range are invalid. (line 290, file "gesi", project "GESI")

I just installed the addon and clicked on authorize charecters

**Comment by Blacksmoke16** [comment]
Ah my bad, this would happen when you are trying to use a character in a function that is no yet authed.  I have a fix to make it more clear in the works.
