### ISSUE TITLE
ESI load

### ISSUE THREAD

**Issue by Gr4vity** [Blacksmoke16/GESI#43]
When I try to load any data through characters_character_industry_jobs or characters_character_assets.

Even when I try to "refresh" token allowing again a user I got this error message : 

SyntaxError: Unexpected token: < (ligne 308, fichier "gesi", projet "GESI")

it's french, ligne mean line, fichier => file and projet => project.

Thanks :)

**Comment by Blacksmoke16** [comment]
I'm going to close this as this is more so todo with CCP and ESI than gesi itself.
