### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by Darkmift** [Blacksmoke16/GESI#44]
I am trying to authorize characters:

Steps:
-go to add-on tab>GESI>authorize characters
-the EVE login window shows up I log select char>window closes and new tab pops saying:

"Thank you for using GESI Darkmift. You can close this tab."

I close said tab>return to spreadsheet>nothing happens....click add on>GESI and its asking to authorize again.

I will not be surprised if Im doing something wrong.

I would appreciate your help.
Thank you.

**Comment by Darkmift** [comment]
sorry got the link from a friend just now saw the git instructions.

**Comment by Blacksmoke16** [comment]
The only thing authing a char does on its own is add/update a row in the hidden `Auth Data` sheet.  If you get the thank you message everything saved correctly.  You then need to do stuff in the sheet to get your data.

Like call `=characters_character_assets()` in a cell.

**Comment by Darkmift** [comment]
so sorry :P thank you.
