### ISSUE TITLE
universe_ids does not return the expected values

### ISSUE THREAD

**Issue by kshood** [Blacksmoke16/GESI#50]
universe_ids is not returning ID data for the supplied names.

When I run the following

function testFunc() {
  var all_sheets = SpreadsheetApp.getActiveSpreadsheet();
  var test_sheet = all_sheets.getSheets()[0]
  data = GESI.universe_ids(['pyerite', 'catalyst'])
  for (var i = 0; i < data.length; i++) {
    test_sheet.appendRow(data[i]);
  }
}

I get the following output:

agents | alliances | characters | constellations | corporations | factions | inventory_types | regions | stations | systems
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
undefined | [{"id":99008933,"name":"Phantom Commando"},{"id":99004764,"name":"Cattery"}] | undefined | undefined | [{"id":1000014,"name":"Perkone"},{"id":1000064,"name":"Carthum Conglomerate"}] | undefined | undefined | undefined | undefined | undefined

Directly using https://esi.evetech.net/ui/ gives the expected values.

The expected values would include the ID information for Pyerite and Catalysts. Instead, this is returning a single row through some logic I really don't understand.

**Comment by Blacksmoke16** [comment]
Because of how Google Sheets works; I made this function work like how it would be used.  I.e. called on a vertical range of type_names.  Because of this if you are going to use it in a custom function you'd have to have a 2D array, like `[['Pyerite'], ['Catalyst']]` for it to work properly.

**Comment by kshood** [comment]
Ah, I see. Thank you for your quick reply.
