### ISSUE TITLE
Cannot add character

### ISSUE THREAD

**Issue by brygphilomena** [Blacksmoke16/GESI#52]
{"body":"{\"error\":\"Not found\"}","code":404,"path":"https://esi.evetech.net/v1/characters/affiliation/","sheet_id":"1-TfHicMlu-qoH5om1454hJbEC12RqIJKnjuGtz8aE2Q","character":null} (line 291, file "gesi", project "GESI")

**Comment by Blacksmoke16** [comment]
@brygphilomena This actually isn't a GESI issue.  ESI is just having issues with that endpoint.  Just try again in a bit.

Can use https://status.esiknife.space/?endpoints=c75893 to monitor the status of it.
