### ISSUE TITLE
Missing ; before statement

### ISSUE THREAD

**Issue by quackmobile** [Blacksmoke16/GESI#53]
I'm trying to use GESI according to the walkthrough here: https://developers.eveonline.com/blog/article/using-esi-with-google-sheets but I keep getting prompted that I'm missing a ; (semicolon) before the statement on line 8 of the GESI file. Is there a fix for this? I don't understand coding at all so I don't want to accidentally break something.

**Comment by Blacksmoke16** [comment]
![image](https://user-images.githubusercontent.com/12136995/58652069-bc015580-82e0-11e9-87ac-edc7f9940d34.png)

See the big text at top of article.
