### ISSUE TITLE
Google Add-On unverified

### ISSUE THREAD

**Issue by Tuxprogrammer** [Blacksmoke16/GESI#54]
Looks like google might have shadowbanned the addon. I can't add it to my sheets because a weird window pops up:
![image](https://user-images.githubusercontent.com/8989940/70884289-3baff280-1f9b-11ea-9ab5-580b36ecff19.png)

It appears you need to go through a validation step to make sure your addon isn't scraping people's google account info.

**Comment by Tuxprogrammer** [comment]
Clicking the "Go to GESI" link appears to have added it to my sheet now, but still unnerving to see this popup before installing it.

**Comment by Blacksmoke16** [comment]
FWIW I submitted GESI for verification ages ago and it's still pending review

![image](https://user-images.githubusercontent.com/12136995/71010205-7c059280-20b9-11ea-8cbe-a522a5a4d8d2.png)


Going to close this as this isn't directly related to GESI itself nor is actionable at the moment.

**Comment by KomAuras** [comment]
Still waiting.

**Comment by Blacksmoke16** [comment]
This is resolved.
