### ISSUE TITLE
Google is blocking GESI install.

### ISSUE THREAD

**Issue by joaorsbarbosa** [Blacksmoke16/GESI#55]
Hi! Whenever I try to install GESI, I get the following error:

"Sign in with Google temporarily disabled for this app

This app has not yet been verified by Google in order to use Google Sign in."

**Comment by Blacksmoke16** [comment]
Yes, I'm aware.  See https://github.com/Blacksmoke16/GESI/issues/54.  I'm talking with the Google Verification people to resolve this.

**Comment by Blacksmoke16** [comment]
This is resolved.
