### ISSUE TITLE
Auth not being recognized, and 1 other

### ISSUE THREAD

**Issue by NexusDarkshade** [Blacksmoke16/GESI#60]
As stated in the title, despite have an authorized character, an error occurs when calling some functions:
`Error: No characters have been authenticated. Visit Add-ons => GEST => Authorize Character to do so. (line 100)`

Also, the following error occurs whenever `GESI.markets_region_orders` is called:
`Error: {id} is not authed, or is misspelled. (line 102)`
where {id} is the type_id passed to `GESI.markets_region_orders`.

**Comment by Blacksmoke16** [comment]
@NexusDarkshade Try it again.  I rolled the add-on back to a working version.  Probably tried to use it when I was testing the new version before rolling back.

**Comment by NexusDarkshade** [comment]
I tried again with version 13, even deleting the previous character authorization and adding a new one, but it didn't work. So, I went back to the last update that worked, and both issues seemed to pop up beginning with version 12.

Version 11 no longer works for different reasons, so I will keep trying older versions until one works.

**Comment by Blacksmoke16** [comment]
You would need to go back to version 11.  

> Version 11 no longer works for different reasons,

I'm assuming you mean to the `not_found` error when using the asset functions?  This will be resolved when I get this new version working.  Until then you can pass `"v5"` to the `version` argument.

**Comment by NexusDarkshade** [comment]
That is indeed the error. Is this the proper way to change the function version?
`GESI.characters_character_assets(version="v5")`

**Comment by Blacksmoke16** [comment]
No, it would be the last parameter.

`GESI.characters_character_assets(,,,"v5")` would keep the defaults on the other parameters.

**Comment by NexusDarkshade** [comment]
I get an unexpected token error from the commas.

**Comment by Blacksmoke16** [comment]
Use `;` if thats what you use in your country, or whichever separator.

**Comment by NexusDarkshade** [comment]
I got around the error by using `undefined` as the unused arguments. Since that's what JS does with unused parameters anyways, it shouldn't change the output. It is now behaving properly.
