### ISSUE TITLE
My spreadsheet couldn't use GESI functions 

### ISSUE THREAD

**Issue by majieaug** [Blacksmoke16/GESI#61]
I followed the GESI readme but My spreadsheet couldn't use GESI functions . I am not sure the GESI script had loaded.
Is there any way to confirm？The page of Script Editor is blank.
![20200416233518](https://user-images.githubusercontent.com/63802184/79475958-fb40ae00-803a-11ea-84d2-b3c3805a705e.jpg)

**Comment by Blacksmoke16** [comment]
Change the version back to `11` for now.
