### ISSUE TITLE
Functions throwing sytax error

### ISSUE THREAD

**Issue by massivepirate** [Blacksmoke16/GESI#62]
I've had GESI set up for a long time and working as intented, but today had to re-auth a character. After I did, some functions throw the error: `SyntaxError: Unexpected token: u (line 74).`.

One that's doing that: `=ARRAYFORMULA(universe_ids(TRIM(A3:A),,False))`

A3:A is a list of Character names.

After checking the docs, I also added a fouth column: '=ARRAYFORMULA(universe_ids(TRIM(A3:A),,False,))`
And tried: `=ARRAYFORMULA(universe_ids(TRIM(A3:A),undefined,False,undefined))`

No change.

**Comment by Blacksmoke16** [comment]
This should be fixed now.  I'm currently testing a new version of GESI and fixing issues as they turn up.  Come join the GESI Discord server for announcements and such https://discord.gg/eEAH2et.
