### ISSUE TITLE
Authorised Characters not added to sheet

### ISSUE THREAD

**Issue by wengole** [Blacksmoke16/GESI#67]
I've added the add-on, followed the steps to authorise a character (on Firefox so had to right-click), get the "success" message, close the tab and return to Sheets but the modal dialog doesn't close, and when I manually close it, the hidden sheet isn't added (View -> Hidden sheets is greyed out) and none of the GESI functions work with error messages to the effect of "no authorised character"

On Chrome the modal closes, but the hidden sheet still isn't added and functions still don't work

**Comment by wengole** [comment]
OK, so still no hidden sheet, but data is starting to come in. I'm assuming it was caching/slowness on ESI.

**Comment by Blacksmoke16** [comment]
As per https://github.com/Blacksmoke16/GESI/releases/tag/8.0.0, that hidden sheet is no longer used.
