### ISSUE TITLE
not authed, or is misspelled.

### ISSUE THREAD

**Issue by jubae** [Blacksmoke16/GESI#69]
Hi,

Firstly thank you for this amazing addon, it is a great accomplishment!!

I am just having issues getting my characters authorised. I follow the process and get the characters authorised fine (I can set my main character once it has been added, which tells me there was no issue).

The issue comes when the sheet (not mine, an old Google sheet project of someone else, trying to get it to work again) tries to pull the data, it just keeps throwing out that the chracter is not Authed, message below : 

Error: #### is not authed, or is misspelled. (line 146, file "gesi")

I get this error no matter how many characters I try it with or what the scope of the authorization is. I have the library installed correctly also.

I can share the sheet I am using if needed, like I Said, its not my sheet originally, I am just trying to get it working again.

Thanks for any help

**Comment by Blacksmoke16** [comment]
Be sure to update the script version.

Can follow https://github.com/Blacksmoke16/GESI#script-editor and just select the latest version.

**Comment by jubae** [comment]
Hi,

Thanks for your response, I have the script updated and have tried all the versions including the latest and still the same result.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Blacksmoke16** [comment]
Hmm.  I assume you have the add-on installed as well?  I'd suggest join the GESI Discord server.  Be easier to figure it out on there.

https://discordapp.com/invite/eEAH2et
