### ISSUE TITLE
Calling Alliance Names turns out as url length error

### ISSUE THREAD

**Issue by Errious** [Blacksmoke16/GESI#7]
When calling =allianceNames() from alliance_ids it seems it has a hard limit on the url lenght, not sure if google is giving out this limit or the api itself but its not possible to call more then 100 for me.

The same occurs when using =corporationNames() from corporation_ids to get the names, i whrote my own part for this and it came up with the same issue, i called the goon id and they have more then 500 corporations, but calling more then 100 was also giving back url length error.

Regards Samuel

**Comment by Blacksmoke16** [comment]
@Errious 

Thanks for the heads up!

This is expected behavior for the ESI endpoint, as the max number of IDs is 100.

I have some ideas for a solution that I will look into for these Name type endpoints.

**Comment by Blacksmoke16** [comment]
Fixed in 2.3.1
