### ISSUE TITLE
JSON.parse().forEach is not working for now

### ISSUE THREAD

**Issue by instkffff** [Blacksmoke16/GESI#72]
TypeError: JSON.parse(...).forEach is not a function (line 95).

So...
parseArray() need to fix.

**Comment by Blacksmoke16** [comment]
Be sure you have V8 enabled.

https://developers.google.com/apps-script/guides/v8-runtime#enabling_the_v8_runtime

**Comment by instkffff** [comment]
I have V8 enabled by default.
Got this result.
![image](https://user-images.githubusercontent.com/3518214/89655874-4f7ae100-d8fd-11ea-98c6-65c2092f3bdf.png)

**Comment by Blacksmoke16** [comment]
Why are you using `parseArray` with that endpoint?  `parseArray` is only needed for functions that return nested arrays, like `characters_character_skills`.  See https://github.com/Blacksmoke16/GESI#why-does-this-cell-contain-all-this-random-data.

Just do `=universe_types_type(34)` and it should be fine.
