### ISSUE TITLE
Access missing and cannot re-auth

### ISSUE THREAD

**Issue by rossos** [Blacksmoke16/GESI#73]
I've been using GESI in my google sheets script for several weeks now. Today, after several tries over several hours, my usual functions would not pull data from ESI. Checking the Stackdriver logs in Google, I see each of the failed calls from the past couple hours giving the same error:

`Error: Access not granted or expired.
    at Service_.getAccessToken(Service:454:11)`

Assuming something might have gone wrong with my character authorization, I just tried to re-auth using the GESI -> Authorize Character menu option. After authenticating with CCP, I was given this error by script.google.com:

`Exception: Data storage error (line 263, file "gesi")`

**Comment by rossos** [comment]
Probably not something you can fix; since reporting, I came across this, which is likely the source of the problem:

https://issuetracker.google.com/issues/162647522

**Comment by Blacksmoke16** [comment]
Yea most likely a Google issue.  I'd just try again later.
