### ISSUE TITLE
Character asset name error

### ISSUE THREAD

**Issue by john2288** [Blacksmoke16/GESI#80]
I am attempting to run characters_character_assets_names, it returns an error - Error: {"error":"Not found"} (line 184).
I have tried multiple different id's with the same result. 

when I run them through the evetech site using the /characters/{character_id}/assets/names/ endpoint, I get the expected result.

**Comment by Blacksmoke16** [comment]
@john2288 I'm unable to reproduce this.  Can you share what the GESI function call you're using looks like?

**Comment by john2288** [comment]
Thanks for the quick response, upon retyping the function call to get it for you i solved the issue. for the ESI version i had originally typed "Latest", this time i typed "latest" and it worked.  fooled by a capital :)

**Comment by Blacksmoke16** [comment]
@john2288 :+1:.  FWIW you don't need to provide those arguments if you don't have a reason to `=characters_character_assets_names(A1:A100)` is sufficient and will just use the defaults for the other arguments.
