### ISSUE TITLE
Standings fetch decimal places

### ISSUE THREAD

**Issue by arhontis** [Blacksmoke16/GESI#81]
Hello, I have been trying the api and it works just fine.

But, I am fetching the standings and I see that the result does not include all the decimals from ESI.

For example I use the function:
=characters_character_standings(B1, true, "latest")
And it returns i.e. for caldari navy the value: 
5.674994141000000
But when I cross check it with eveskillboard that does the same thing, it shows:
5.6749941419931

Would it be possible to not truncate the last digits and include all to the result?

Thanks in advance.

**Comment by Blacksmoke16** [comment]
GESI just returns what ESI returns, so if there's a discrepancy I would wait like an hour and try again as both Google and ESI cache data.  It's possible that eveskillboard has newer/older data than you're seeing now.

I tried this with my own standings and asserted that it returns exactly what ESI returns.

**Comment by Blacksmoke16** [comment]
Feel free to re-open if you're able to reproduce this.
