### ISSUE TITLE
POST characters_character_mail method

### ISSUE THREAD

**Issue by iaaaan** [Blacksmoke16/GESI#84]
Hi,

First I'd like to thank you for this amazing project and equally impressive documentation. I am new to the community but I can see how projects like this make Eve so rich. Congratulations!

One thing I wasn't able to do so far is using GESI to send  a POST request to the /characters/{character_id}/mail/ endpoint. If I'm not mistaken, I think the characters_character_mail method only routes to the GET version of the endpoint. Is there any plan in the future to include the POST endpoint as well?

Here's my use case: after automatically computing some numbers in my spreadsheet, I'd like to send myself a neat daily report that I would receive ingame. This would allow me to use my google sheet data without switching back and forth between my browser and eve client.

Thank you for your time!

**Comment by Blacksmoke16** [comment]
@iaaaan No problem glad to hear :)

But no, there are no plans to support `POST` based endpoints. The main reason for this is they do not play nicely with a spreadsheet. I.e. you wouldn't want to send a mail every time someone loads the sheet. However, that doesn't mean it's impossible to do yourself.

You would need to construct the request as per https://esi.evetech.net/ui/#/Mail/post_characters_character_id_mail,then send it via https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app#fetchurl,-params. You can use a GESI client to get a token for the user that should send it as well. Something like:

```js
const token = GESI.getClient('Blacksmoke16').getAccessToken();
```
