### ISSUE TITLE
universe_structures_structure request error

### ISSUE THREAD

**Issue by multru** [Blacksmoke16/GESI#86]
I receive this kind of error when trying to take structure data automatically with google script code
Error: {"error":"Forbidden"}
doRequest
execute
invoke
universe_structures_structure

What does it mean and can I skip this kind of errors?

**Comment by Blacksmoke16** [comment]
Oops, sorry for the delay @multru!

For your use case I would suggest to keep a static list and just `vlookup` the names of each location. This way you avoid making extra requests which will make things more performant. It also allows you to give custom names to each structure if you actually know the name but it's unresolveable via ESI.

Another option would be to move your logic into a custom function which would allow using JS exception handling features.

Feel free to stop by the Discord server if you want to chat about it more.

**Comment by multru** [comment]
thx for your reply @Blacksmoke16 
the exception is a great idea! I just forgot about this )
About performance, this script is built my static table. Because in a first way I'm checking if these names (stations, characters, ships) are already present in my table, and if no I request this data by GESI.
Issue is closed.
