### ISSUE TITLE
Can't get data from characterPlanetsDetail function call

### ISSUE THREAD

**Issue by EveMarketDude** [Blacksmoke16/GESI#9]
The characterPlanetsDetail function call is returning the following error: "TypeError: Cannot read property "planet_id" from undefined. (line 1080)."

I've tried to provide the first parameter in the function call as an actual number:  12345678 and as a cell based upon the results of a characterPlanets call.

If I hard code a planet_id value (12345678) between line 850 and 851, the function characterPlanetDetails starting at line 1322 has a parameter planet_id value of: {planet_id=1.2345678E7}

Perhaps the conversion to scientific notation is causing the error?

**Comment by Blacksmoke16** [comment]
Issue was i never updated the custom planetDetails function to use the new get data format.

Fixed in 3.0.1

**Comment by EveMarketDude** [comment]
That fixed it. Thanks for the quick response and great script!
