### ISSUE TITLE
GESI is missing from Google Sheets Add-Ons

### ISSUE THREAD

**Issue by NomadThanatos** [Blacksmoke16/GESI#90]
The search result is empty and the link return 400 error.

https://workspace.google.com/marketplace/app/gesi/747777332185

**Comment by Blacksmoke16** [comment]
Known issue. I messed something up in GCP, so waiting on Google to approve it again. Should hopefully be back in a day or so. My bad.

**Comment by richieknight** [comment]
Hey @Blacksmoke16 . Is there any update on this issue? It's still not visible. Thanks.

**Comment by cbrothers** [comment]
He's posted updates on his discord server on status.  There are some known workarounds if you have existing sheets with chars that don't need new auth.  but until Google gets the addon back in the store, you won't be able to auth new chars or create new sheets.

GESI Discord Server: https://discordapp.com/invite/eEAH2et

**Comment by Blacksmoke16** [comment]
It's back.
